### ISSUE TITLE
is endpoints/restricted in role definition absolutely necessary?

### ISSUE THREAD

**Issue by dpotapov** [timescale/helm-charts#114]
I don't have cluster-wide access to Kubernetes I'm deploying to. Thus the chart won't install saying:

```
attempting to grant RBAC permissions not currently held: {APIGroups:[""], Resources:["endpoints/restricted"], Verbs:["create" "get" "patch" "update" "list" "watch" "delete"]}
``` 

Can there be a solution for this?

**Comment by feikesteenbergen** [comment]
No, it is not required for all Kubernetes deployments, only for OpenShift, it was added due to this:

https://github.com/timescale/timescaledb-kubernetes/issues/91
