### ISSUE TITLE
Auto add EXTENSION

### ISSUE THREAD

**Issue by rbdevops** [timescale/helm-charts#184]
How i can add the shared_preload_libraries = 'pg_stat_statements' parameter to postgresql.conf;
and create an extension in the postgres itself: CREATE EXTENSION pg_stat_statements.
through helm chart?

**Comment by feikesteenbergen** [comment]
>How i can add the shared_preload_libraries = 'pg_stat_statements' parameter to postgresql.conf;

The `pg_stat_statements` is already included in the `shared_preload_libraries` by default, see:

https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml#L165

If you want to add more libraries, that would be the thing to change.

> and create an extension in the postgres itself: CREATE EXTENSION pg_stat_statements.
through helm chart?

That can be done by using callbacks, they are very flexible, but also quite a lot of moving parts to get where you want.
https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#callbacks

Issue #102 seems like a relevant one here, adding a post-init script, which would allow you to, for example do

```sql
\connect template1 postgres
CREATE EXTENSION pg_stat_statements;
```
