### ISSUE TITLE
Postgres-exporter service and port selection

### ISSUE THREAD

**Issue by jpigree** [timescale/helm-charts#237]
Hi, I use the PrometheusOperator to manage my Prometheus instance (externally from timescale charts) and scrape the postgres-exporter endpoint. However, I couldn't select the correct port to scrape either in my PodMonitor or my ServiceMonitor objects because the postgres-exporter service has no specific label and its ports either in the Statefulset or in the service are unnamed.

Currently, my workaround is to patch the service created by the chart with a new label to be able to select it.

I created a PR(#233) to fix this. The PR adds labels to the service and name the ports so it shouldn't break anything.

**Comment by paulfantom** [comment]
Closing as https://github.com/timescale/helm-charts/pull/233 is already merged.
