### ISSUE TITLE
[Question] Timescale Multi-node setup

### ISSUE THREAD

**Issue by pratapagiri** [timescale/helm-charts#251]
Could you please let us know whether Timescale multi-node setup is opensource (covered under Apache 2)?

**Comment by paulfantom** [comment]
Helm chart is covered under Apache 2. TimescaleDB itself is not.

Additionally we are sorry to say that multinode helm chart is deprecated and not supported anymore. If you want to see this chart supported then we are looking for community maintainers - https://github.com/timescale/helm-charts/tree/master/charts/timescaledb-multinode#call-for-maintainers
