### ISSUE TITLE
If patroni.kubernetes.use_endpoints=false, no obvious way to find the master

### ISSUE THREAD

**Issue by ellieayla** [timescale/helm-charts#278]
**Describe the bug**

I think that normally Patroni is responsible for managing the Endpoints of the chart's primary Service, defined in https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/templates/svc-timescaledb.yaml

I am deploying this chart with FluxCD. I have been setting patroni.kubernetes.use_endpoints=false so Flux and Patroni are not both trying to manipulate the same Service.

If patroni.kubernetes.use_endpoints=false, Patroni doesn't create any Endpoints here. There is no obvious way for an app inside the cluster to find the pod with `role=master`.

**To Reproduce**

`helm install --version 0.8.2 timescaledb timescale/timescaledb-single --set loadBalancer.enabled=false --set patroni.kubernetes.use_endpoints=false`

```
kubectl describe svc timescaledb
Name:              timescaledb
Namespace:         default
Labels:            app=timescaledb
                   app.kubernetes.io/managed-by=Helm
                   chart=timescaledb-single-0.8.2
                   cluster-name=timescaledb
                   heritage=Helm
                   release=timescaledb
                   role=master
Annotations:       meta.helm.sh/release-name: timescaledb
                   meta.helm.sh/release-namespace: default
                   service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 4000
Selector:          <none>           <---- no selector
Type:              ClusterIP
IP:                10.103.188.137
Port:              postgresql  5432/TCP
TargetPort:        postgresql/TCP
Endpoints:         <none>           <---- no endpoints
Session Affinity:  None
Events:            <none>
```

There is a pod with label `role=master`.

```
kubectl get pods -l app=timescaledb,cluster-name=timescaledb,role=master --show-labels
NAME            READY   STATUS    RESTARTS   AGE   LABELS
timescaledb-0   1/1     Running   0          18m   app=timescaledb,cluster-name=timescaledb,controller-revision-hash=timescaledb-56648cf465,release=timescaledb,role=master,statefulset.kubernetes.io/pod-name=timescaledb-0
```

Pods with label `role=replica` are normally discovered by the `timescaledb-replica` service's label selector like normal.

**Expected behavior**

When `patroni.kubernetes.use_endpoint=False`, define a label selector for the `timescaledb` service.

**Deployment**
- What is in your `values.yaml`

```
loadBalancer:
   enabled: false
patroni:
   kubernetes:
       use_endpoints: false
```

- What version of the Chart are you using? 0.8.2
- What is your Kubernetes Environment: docker-desktop & aks

**Deployment**
Please share some details of what is in your Kubernetes environment, for example:

```
kubectl get all,secret,configmap,endpoints,pvc -L role -l release=$RELEASE
```

**Logs**
Unimporant

**Additional context**

**Comment by feikesteenbergen** [comment]
The design of this Helm charts assumes `use_endpoints=true`.

**Comment by agronholm** [comment]
How is one supposed to connect to the master using `kubectl port-forward` when there are no selectors in the master service?

**Comment by Hongbo-Miao** [comment]
I had same question about how to port-forward without selector. So I created a **my-values.yaml** file

```
service:
  primary:
    spec:
      selector:
        app: timescale-timescaledb
        role: master
```

Then installed by 

```
helm install timescale  timescale/timescaledb-single --values=kubernetes/manifests/timescale/helm/my-values.yaml
```

**Comment by auyer** [comment]
You are a life saver @Hongbo-Miao !
Not sure the relation to this issue, but I do believe this is a bug. Could you create an issue about it ?

**Comment by agronholm** [comment]
Isn't this it?

**Comment by fungiboletus** [comment]
Can we reopen the issue ?
