### ISSUE TITLE
[Question] How to set priorityClassName

### ISSUE THREAD

**Issue by mralexes** [timescale/helm-charts#290]
Hey, folks. 
Is there any way to specify [priorityClassName](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#pod-priority) for TSDB pods?

**Comment by djhaskin987** [comment]
Yes please :) I would like to set priorityClassName very much.

**Comment by nhudson** [comment]
I am going to mark this as a duplicate request of #382 which also has a PR already that does need some love ( #390 ).  We are working on adding some of these features into the chart.  So hopefully this can get incorporated soon.
