### ISSUE TITLE
TimescaleDB Tune Always tunes for PostgreSQL 11

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/helm-charts#294]
`timescaledb-tune` used to not support PostgreSQL 12/13, and therefore this line:

```yaml
timescaledb-tune -quiet -pg-version 11 -conf-path "${TSTUNE_FILE}" -cpus "${CPUS}" -memory "${MEMORY}MB"
```

Is a bit outdated; we can drop the `-pg-version 11` here.

**Comment by agronholm** [comment]
I have forked the official timescaledb chart here: https://github.com/agronholm/timescaledb-kubernetes
See the installation instructions there. This is one of the issues the fork seeks to resolve. Let me know if this resolved the problem for you.

**Comment by mindrunner** [comment]
@agronholm Can you open Pull Requests to get your changes into the official chart?
