### ISSUE TITLE
Helm install with default values.yaml not working

### ISSUE THREAD

**Issue by pankaj-83incs** [timescale/helm-charts#322]
**Describe the bug**

Events:
  Type     Reason       Age              From               Message
  ----     ------       ----             ----               -------
  Normal   Scheduled    5s               default-scheduler  Successfully assigned default/pankaj-timescaledb-0 to ip-172-31-59-26
  Warning  FailedMount  1s (x3 over 2s)  kubelet            MountVolume.SetUp failed for volume "certificate" : secret "pankaj-certificate" not found

**To Reproduce**

Pull the helm chart and run helm install <release-name> timescaledb-single

**Expected behavior**
Timescale DB should start immediately with default values.yaml

**Logs**
ubuntu@ip-172-31-59-26:~/app-iaac-keysight$ kubectl describe po pankaj-timescaledb-0
Name:           pankaj-timescaledb-0
Namespace:      default
Priority:       0
Node:           ip-172-31-59-26/
Labels:         app=pankaj-timescaledb
                cluster-name=pankaj
                controller-revision-hash=pankaj-timescaledb-6bfdcdb479
                release=pankaj
                statefulset.kubernetes.io/pod-name=pankaj-timescaledb-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/pankaj-timescaledb
Init Containers:
  tstune:
    Image:      timescaledev/timescaledb-ha:pg12-ts2.0-latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      set -e
      [ $CPUS -eq 0 ]   && CPUS="${RESOURCES_CPU_LIMIT}"
      [ $MEMORY -eq 0 ] && MEMORY="${RESOURCES_MEMORY_LIMIT}"
      
      if [ -f "${PGDATA}/postgresql.base.conf" ] && ! grep "${INCLUDE_DIRECTIVE}" postgresql.base.conf -qxF; then
        echo "${INCLUDE_DIRECTIVE}" >> "${PGDATA}/postgresql.base.conf"
      fi
      
      touch "${TSTUNE_FILE}"
      timescaledb-tune -quiet -pg-version 11 -conf-path "${TSTUNE_FILE}" -cpus "${CPUS}" -memory "${MEMORY}MB" \
         -yes
      
      # If there is a dedicated WAL Volume, we want to set max_wal_size to 60% of that volume
      # If there isn't a dedicated WAL Volume, we set it to 20% of the data volume
      if [ "${RESOURCES_WAL_VOLUME}" = "0" ]; then
        WALMAX="${RESOURCES_DATA_VOLUME}"
        WALPERCENT=20
      else
        WALMAX="${RESOURCES_WAL_VOLUME}"
        WALPERCENT=60
      fi
      
      WALMAX=$(numfmt --from=auto ${WALMAX})
      
      # Wal segments are 16MB in size, in this way we get a "nice" number of the nearest
      # 16MB
      WALMAX=$(( $WALMAX / 100 * $WALPERCENT / 16777216 * 16 ))
      WALMIN=$(( $WALMAX / 2 ))
      
      echo "max_wal_size=${WALMAX}MB" >> "${TSTUNE_FILE}"
      echo "min_wal_size=${WALMIN}MB" >> "${TSTUNE_FILE}"
      
    Environment:
      TSTUNE_FILE:             /var/run/postgresql/timescaledb.conf
      RESOURCES_WAL_VOLUME:    1Gi
      RESOURCES_DATA_VOLUME:   2Gi
      INCLUDE_DIRECTIVE:       include_if_exists = '/var/run/postgresql/timescaledb.conf'
      CPUS:                    0 (requests.cpu)
      MEMORY:                  0 (requests.memory)
      RESOURCES_CPU_LIMIT:     node allocatable (limits.cpu)
      RESOURCES_MEMORY_LIMIT:  node allocatable (limits.memory)
    Mounts:
      /var/run/postgresql from socket-directory (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5xrgn (ro)
Containers:
  timescaledb:
    Image:       timescaledev/timescaledb-ha:pg12-ts2.0-latest
    Ports:       8008/TCP, 5432/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      
      install -o postgres -g postgres -d -m 0700 "/var/lib/postgresql/data" "/var/lib/postgresql/wal/pg_wal" || exit 1
      TABLESPACES=""
      for tablespace in ; do
        install -o postgres -g postgres -d -m 0700 "/var/lib/postgresql/tablespaces/${tablespace}/data"
      done
      
      # Environment variables can be read by regular users of PostgreSQL. Especially in a Kubernetes
      # context it is likely that some secrets are part of those variables.
      # To ensure we expose as little as possible to the underlying PostgreSQL instance, we have a list
      # of allowed environment variable patterns to retain.
      #
      # We need the KUBERNETES_ environment variables for the native Kubernetes support of Patroni to work.
      #
      # NB: Patroni will remove all PATRONI_.* environment variables before starting PostgreSQL
      
      # We store the current environment, as initscripts, callbacks, archive_commands etc. may require
      # to have the environment available to them
      set -o posix
      export -p > "${HOME}/.pod_environment"
      export -p | grep PGBACKREST > "${HOME}/.pgbackrest_environment"
      
      for UNKNOWNVAR in $(env | awk -F '=' '!/^(PATRONI_.*|HOME|PGDATA|PGHOST|LC_.*|LANG|PATH|KUBERNETES_SERVICE_.*)=/ {print $1}')
      do
          unset "${UNKNOWNVAR}"
      done
      
      touch /var/run/postgresql/timescaledb.conf
      touch /var/run/postgresql/wal_status
      
      echo "*:*:*:postgres:${PATRONI_SUPERUSER_PASSWORD}" >> ${HOME}/.pgpass
      chmod 0600 ${HOME}/.pgpass
      
      export PATRONI_POSTGRESQL_PGPASS="${HOME}/.pgpass.patroni"
      
      exec patroni /etc/timescaledb/patroni.yaml
      
    Readiness:  exec [pg_isready -h /var/run/postgresql] delay=5s timeout=5s period=30s #success=1 #failure=6
    Environment Variables from:
      pankaj-credentials  Secret  Optional: false
      pankaj-pgbackrest   Secret  Optional: true
    Environment:
      PATRONI_admin_OPTIONS:               createrole,createdb
      PATRONI_REPLICATION_USERNAME:        standby
      PATRONI_KUBERNETES_POD_IP:            (v1:status.podIP)
      PATRONI_POSTGRESQL_CONNECT_ADDRESS:  $(PATRONI_KUBERNETES_POD_IP):5432
      PATRONI_RESTAPI_CONNECT_ADDRESS:     $(PATRONI_KUBERNETES_POD_IP):8008
      PATRONI_KUBERNETES_PORTS:            [{"name": "postgresql", "port": 5432}]
      PATRONI_NAME:                        pankaj-timescaledb-0 (v1:metadata.name)
      PATRONI_POSTGRESQL_DATA_DIR:         /var/lib/postgresql/data
      PATRONI_KUBERNETES_NAMESPACE:        default
      PATRONI_KUBERNETES_LABELS:           {app: pankaj-timescaledb, cluster-name: pankaj, release: pankaj}
      PATRONI_SCOPE:                       pankaj
      PGBACKREST_CONFIG:                   /etc/pgbackrest/pgbackrest.conf
      PGDATA:                              $(PATRONI_POSTGRESQL_DATA_DIR)
      PGHOST:                              /var/run/postgresql
      BOOTSTRAP_FROM_BACKUP:               0
    Mounts:
      /etc/certificate from certificate (ro)
      /etc/pgbackrest from pgbackrest (ro)
      /etc/pgbackrest/bootstrap from pgbackrest-bootstrap (ro)
      /etc/timescaledb/patroni.yaml from patroni-config (ro,path="patroni.yaml")
      /etc/timescaledb/post_init.d from post-init (ro)
      /etc/timescaledb/scripts from timescaledb-scripts (ro)
      /var/lib/postgresql from storage-volume (rw)
      /var/lib/postgresql/wal from wal-volume (rw)
      /var/run/postgresql from socket-directory (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5xrgn (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  storage-volume-pankaj-timescaledb-0
    ReadOnly:   false
  wal-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wal-volume-pankaj-timescaledb-0
    ReadOnly:   false
  socket-directory:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  patroni-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pankaj-timescaledb-patroni
    Optional:  false
  timescaledb-scripts:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pankaj-timescaledb-scripts
    Optional:  false
  post-init:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       custom-init-scripts
    ConfigMapOptional:   0xc000d4f818
    SecretName:          custom-secret-scripts
    SecretOptionalName:  0xc000d4f819
  pgbouncer:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pankaj-timescaledb-pgbouncer
    Optional:  true
  pgbackrest:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      pankaj-timescaledb-pgbackrest
    Optional:  true
  certificate:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pankaj-certificate
    Optional:    false
  pgbackrest-bootstrap:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pgbackrest-bootstrap
    Optional:    true
  kube-api-access-5xrgn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age              From               Message
  ----     ------       ----             ----               -------
  Normal   Scheduled    5s               default-scheduler  Successfully assigned default/pankaj-timescaledb-0 to ip-172-31-59-26
  Warning  FailedMount  1s (x3 over 2s)  kubelet            MountVolume.SetUp failed for volume "certificate" : secret "pankaj-certificate" not found

**Comment by JamesGuthrie** [comment]
@pankaj-83incs I ran into this recently as well. It seems as though the most recent chart versions fix the problem that you're running into, but those have not been released on `charts.timescale.com`. I've opened https://github.com/timescale/timescaledb-kubernetes/issues/324 for that.

In the meantime, you should be able to work around this problem with:

```
helm repo add timescale 'https://raw.githubusercontent.com/timescale/timescaledb-kubernetes/master/charts/repo/'
helm update
helm install timescaledb timescale/timescaledb-single
```

**Comment by kbrs-miaha** [comment]
I wanted to concur with the observation that using the repo at `https://charts.timescale.com` and installing `0.8.2` (the most recent release) with default values does not generate any secrets. These have to be created manually and that the format of the `values.yaml` is not consistent with the documentation from the `git` repo.

The workaround is as BlochBK suggests, is to clone the git repo and install from the local copy.

**Comment by paulfantom** [comment]
It seems that issue is already fixed and charts are correctly published. If you find that the problem is still happening in your environment, please reopen this ticket.
