### ISSUE TITLE
If Datanode1 down then corresponding table(stored in datanode1) not giving data while query

### ISSUE THREAD

**Issue by Murugan-mindtree** [timescale/helm-charts#326]
HI Team,

I am using 1 access node, 3 data nodes, we created bunch of tables and inserted data. if one data node is down then the query will not respond the data.

how to resolve the below mentioned issue?

**Comment by paulfantom** [comment]
We are sorry to say that multinode helm chart is deprecated and not supported anymore. If you want to see this chart supported then we are looking for community maintainers - https://github.com/timescale/helm-charts/tree/master/charts/timescaledb-multinode#call-for-maintainers

**Comment by paulfantom** [comment]
I am closing this issue as TimescaleDB-Multinode helm chart is no longer maintained and deprecated. We are looking for potential community maintainers who could help us in getting that helm chart working again. If you wish to become a maintainer, please [contact us on slack](https://timescaledb.slack.com/).

Keep in mind that TimescaleDB is not and will not be dropping multinode setup. Deprecation is only about helm chart.
