### ISSUE TITLE
[Question] Does the repo is not in sync with chart

### ISSUE THREAD

**Issue by this-is-r-gaurav** [timescale/helm-charts#339]
**Describe the bug**
When i was trying to follow up the guide and deploy a release https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#handling-secrets. According to it, it should generate secret certificate and everything, if not filled in values.yaml. But it is not generating certificate. When i untar any of the chart there i found admin-guide.md which says secret are needed to generate before hand

**To Reproduce**
```
helm repo add timescaledb 'https://raw.githubusercontent.com/timescale/timescaledb-kubernetes/master/charts/repo/'
helm show values > values.yaml
# fill basic details other than secret information
helm install -f values.yaml timescaledb/timescaledb-single
```

**Expected behavior**
Certificate should be generated beforehand without manual intervention.

**Additional Details**
![image](https://user-images.githubusercontent.com/25682376/154398693-fe02e23f-6f5f-49e6-8aae-188319baf683.png)

If something is changed will it be the behavior in upcoming release.

**Comment by paulfantom** [comment]
This should've been already fixed. Please reopen if you still see this issue happening.
