### ISSUE TITLE
[Multinodes] no pg_hba.conf entry

### ISSUE THREAD

**Issue by gchicoye** [timescale/helm-charts#341]
Hi,

When setting up TimescaleDB Multinode, I get the following error when trying to connect from a Cluster IP
`no pg_hba.conf entry for host "10.2.0.X", user "postgres", database "postgres", SSL off`

The steps to reproduce are as follow (I've followed this tutorial https://praveenperera.com/blog/install-timescale-2-0-on-kubernetes)
* I clone the repository, and use [timescaledb-kubernetes](https://github.com/timescale/timescaledb-kubernetes)/[charts](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts)/timescaledb-multinode/
* I update templates/svc-timescaledb-access.yaml with spec type to `ClusterIp`
* I run `helm install timescale-db timescaledb-multi-charts --namespace=default` with the charts in ./timescaledb-multi-charts
* Once all pods are created and everybody seems fine, I try to connect from another pod I create on purpose with `kubectl run -i --tty --rm psql --image=postgres --restart=Never -- bash -il`
*  Within the pod, I try to run `psql -U postgres -h timescale-db-timescaledb.default.svc.cluster.local postgres` and I get the following error
`psql: error: connection to server at "timescale-db-timescaledb.default.svc.cluster.local" (10.3.240.X), port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.2.0.X", user "postgres", database "postgres", SSL off`

I'm a little bit lost on how to fix the pg_hba.conf...

Thanks!

**Comment by gchicoye** [comment]
Hi,

Actually, it appears to be working well with the following configuration
```
image:
  # Image was built from
  # https://github.com/timescale/timescaledb-docker-ha
  repository: timescale/timescaledb-ha
  tag: pg12.5-ts2.0.0-p0
  pullPolicy: IfNotPresent
```

This image is one year old as mentionned here https://hub.docker.com/layers/timescale/timescaledb-ha/pg12.5-ts2.0.0-p0/images/sha256-6290f40c087534acc351a62d4c05a122b3bfd73dd72e5865a6214e4c3471dd1b?context=explore

I've done some tests with pg13.x or pg14.x release, I was facing the same pg_hba.conf issue...
Anything to do to get some recent version?

**Comment by alexeyklyukin** [comment]
```
SSL off
```

Not sure if this is the root cause or a symptom, but what happens if you force SSL on (use `sslmode=require`)?
```
psql  "host=timescale-db-timescaledb.default.svc.cluster.local dbname=postgres user=postgres sslmode=require"
```

Also, does it work if you connect from your local system, not from K8s?

**Comment by gchicoye** [comment]
Hi @alexeyklyukin ,
Indeed, this might be the root cause...
For instance, when I get the access pod logs through `kubectl logs -f timescale-db-timescaledb-access-0` I get the following results (sample below)...

```
2022-03-01 17:13:17 UTC [2155]: [621e542d.86b-1] [unknown]@[unknown],app=[unknown] [00000] LOG:  connection received: host=10.2.0.186 port=42914
2022-03-01 17:13:17 UTC [2155]: [621e542d.86b-2] postgres@postgres,app=[unknown] [28000] FATAL:  no pg_hba.conf entry for host "10.2.0.186", user "postgres", database "postgres", no encryption
```

However, I can't see on multinode `values.yaml` anything about ssl configuration, and there is no equivalent of `configmap-pgbouncer.yaml`.

**Comment by alexeyklyukin** [comment]
@gchicoye you sure the is no
```
hostssl all all all md5
```

in the first image?

**Comment by gchicoye** [comment]
100% sure, I've just done a recheck

**Comment by AlbertoPimpo** [comment]
I have the same issue, any solution?

**Comment by paulfantom** [comment]
Multinode helm chart is deprecated and not supported anymore. If you want to see this chart supported then we are looking for community maintainers - https://github.com/timescale/helm-charts/tree/master/charts/timescaledb-multinode#call-for-maintainers
