### ISSUE TITLE
[Feature Request] Simple non distributed/high availability deployment

### ISSUE THREAD

**Issue by fungiboletus** [timescale/helm-charts#348]
Hi,

Sometimes I want a simple deployment without unnecessary complexity for my use case. Using helm charts for that is still useful.

For example, Bitnami provides two flavours of PostgreSQL helm charts: [the normal standalone PostgreSQL bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql/), and [the PostgreSQL HA bitnami hem chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha/).

I may have a rare use of Timescaledb, so I wouldn't mind at all if you decide against offering a helm chart for that. But maybe there is a demand 🙂

**Comment by paulfantom** [comment]
You can still do that by using timescaledb-single and setting:
```
replicaCount: 1
```

Similarly to how we use it in our tests - https://github.com/timescale/helm-charts/blob/master/Makefile#L50-L62.
