### ISSUE TITLE
Suggestion: Set PATRONICTL_CONFIG_FILE

### ISSUE THREAD

**Issue by jamesprior** [timescale/helm-charts#365]
Per https://patroni.readthedocs.io/en/latest/ENVIRONMENT.html it looks like if you set PATRONICTL_CONFIG_FILE to `/etc/timescaledb/patroni.yaml` in the chart it'd help anyone opening a session on the pod and using patronictl

Not really a bug, just a nice to have.

**Comment by jleni** [comment]
A PR to fix this was just merged

**Comment by nhudson** [comment]
Closing this as this was added in #552
