### ISSUE TITLE
[Feature request] Implement backup restore in helm chart

### ISSUE THREAD

**Issue by AlbertoPimpo** [timescale/helm-charts#366]
Hello,
It would be great to have the possibility to restore a backup during the installation process of the helm chart.
If there is any idea or suggestion on how to do it I will be happy to help with the implementation.
Thanks

**Comment by throrin19** [comment]
Normally it's already in place and works nativelly. I've test that in older version (like the single-node in 0.8) and without make anything, the server start after get backup from my S3 bucket

**Comment by nhudson** [comment]
@throrin19 is correct.  We currently have support for adding configuration to use [pgbackrest](https://pgbackrest.org/) in the timescaledb-single Helm chart.  The configuration for that is located [here](https://github.com/timescale/helm-charts/blob/761e2283995b3b248593cbb0cb5496def1c2815b/charts/timescaledb-single/values.yaml#L55-L129) in the `values.yaml`

**Comment by nhudson** [comment]
@AlbertoPimpo I am going to close this issue since we currently already support backup/restore from S3 using pgbackrest.  If you feel like the issue should be reopened, please do so!  Thanks!!
