### ISSUE TITLE
[ISSUE] EKS 1.21 - BoundServiceAccountTokenVolume refresh token

### ISSUE THREAD

**Issue by mogggggg** [timescale/helm-charts#374]
Hi,
As part of the v1.21 release the BoundServiceAccountTokenVolume feature is enabled by default. We received a notification stating that the `timescale-timescaledb` ServiceAccount does not automatically refresh it's token. Here's a snippet of the notification:

```
We have identified applications running in one or more of your Amazon EKS clusters that are not refreshing service account tokens. Applications making requests to Kubernetes API server with expired tokens will fail. You can resolve the issue by updating your application and its dependencies to use newer versions of Kubernetes client SDK that automatically refreshes the tokens.

What is the problem?

Kubernetes version 1.21 graduated BoundServiceAccountTokenVolume feature [1] to beta and enabled it by default. This feature improves security of service account tokens by requiring a one hour expiry time, over the previous default of no expiration. This means that applications that do not refetch service account tokens periodically will receive an HTTP 401 unauthorized error response on requests to Kubernetes API server with expired tokens. You can learn more about the BoundServiceAccountToken feature in EKS Kubernetes 1.21 release notes [2].

To enable a smooth migration of applications to the newer time-bound service account tokens, EKS v1.21+ extends the lifetime of service account tokens to 90 days. Applications on EKS v1.21+ clusters that make API server requests with tokens that are older than 90 days will receive an HTTP 401 unauthorized error response.

How can you resolve the issue?

To make the transition to time bound service account tokens easier, Kubernetes has updated the below official versions of client SDKs to automatically refetch tokens before the one hour expiration:

* Go v0.15.7 and later
* Python v12.0.0 and later
* Java v9.0.0 and later
* Javascript v0.10.3 and later
* Ruby master branch
* Haskell v0.3.0.0

We recommend that you update your application and its dependencies to use one of the above client SDK versions if you are on an older version.
```

Here's a snippet from the CloudWatch Insights query AWS [advise you to run](https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html#identify-pods-using-stale-tokens):
```
"annotations":{"authentication.k8s.io/stale-token":"subject: system:serviceaccount:datastore:timescale-timescaledb, seconds after warning threshold: 619228"
```

We're using the Helm chart `timescaledb-single` with version v0.11.0 and our Timescale DB image is `timescale/timescaledb-ha:pg13.7-ts2.7.0-latest`

**Comment by noamApps** [comment]
+1 we got this too, I looked a bit into it,  it seems that the problem is that timescale is using patroni v2.1.3 (used AWS CloudWatch to get the user-agent of the client that uses the stale token)

patroni added automatic token refresh in v2.1.4 - https://github.com/zalando/patroni/blob/master/docs/releases.rst#version-214

I pulled timescale/timescaledb-ha:pg14.3-ts2.7.0-p0 which seems to be the latest version, still uses patroni v2.1.3

This will break tsdb deployments  that are running for more than 90days, more about the problem can be found here
https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html

**Comment by mogggggg** [comment]
FYI - the latest image `pg13.7-ts2.7.2-latest` appears to be using Patroni `v2.1.4`. I've just upgraded one of our clusters and haven't seen any stale token warnings in CloudWatch Logs yet.

**Comment by mogggggg** [comment]
Confirming upgrading to the latest image has fixed this.
