### ISSUE TITLE
Multiple access nodes  in multi-node cluster

### ISSUE THREAD

**Issue by albertogg99** [timescale/helm-charts#377]
Hi,

Why the multi-node chart only allows one access node? Shouldn't it be possible to have several replicas of the access node to ensure HA? What happens if this single access node goes down?

**Comment by AkashRajvanshi** [comment]
Hi,

Have you found anything related to this? I'm also checking if a single access node goes down. Then can I create a new access node for the existing cluster, or can we have an option to use streaming replicas and patroni for access_node failover?

**Comment by paulfantom** [comment]
Multinode helm chart is deprecated and not supported anymore. If you want to see this chart supported then we are looking for community maintainers - https://github.com/timescale/helm-charts/tree/master/charts/timescaledb-multinode#call-for-maintainers

**Comment by zfy0701** [comment]
@paulfantom is currently promscale support multi-node timescale now? If so we are happy to help

**Comment by paulfantom** [comment]
Promscale does support multi-node timescale. However, we are not accepting any contributions to a multinode helm chart as it is unmaintained. @zfy0701 do you want to become a community maintainer of that chart?

**Comment by paulfantom** [comment]
I am closing this issue as TimescaleDB-Multinode helm chart is no longer maintained and deprecated. We are looking for potential community maintainers who could help us in getting that helm chart working again. If you wish to become a maintainer, please [contact us on slack](https://timescaledb.slack.com/).

Keep in mind that TimescaleDB is not and will not be dropping multinode setup. Deprecation is only about helm chart.
