### ISSUE TITLE
[ISSUE] For multinode setup repository and image needs to be updated ?

### ISSUE THREAD

**Issue by iliyas-patel-git** [timescale/helm-charts#385]
> Have a look at [Troubleshooting](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#troubleshooting) or some [Common Issues](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#common-issues)

**Describe the bug**
Repository and image in value.yaml needs to be updated to, as current installation is getting failed.
image.tag=pg12.5-ts2.0.0-p0 
image.repository=timescaledev/timescaledb-ha

[timescaledb-kubernetes](https://github.com/timescale/timescaledb-kubernetes)/[charts](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts)/[timescaledb-multinode](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-multinode)/values.yaml

**To Reproduce**
helm upgrade --install my-release .

**Expected behavior**
Installation was successful using below command: 
helm install mnode timescaledb/timescaledb-multinode --set image.tag=pg12.5-ts2.0.0-p0 --set image.repository=timescaledev/timescaledb-ha

**Deployment**
- What is in your `values.yaml` - 
   repository: timescale/timescaledb-ha
  tag: pg12-ts2.0.0-p0

- What version of the Chart are you using? - latest
- What is your Kubernetes Environment  - minikube

**Comment by paulfantom** [comment]
Multinode helm chart is deprecated and not supported anymore. If you want to see this chart supported then we are looking for community maintainers - https://github.com/timescale/helm-charts/tree/master/charts/timescaledb-multinode#call-for-maintainers

**Comment by realulim** [comment]
Can we get some more details? I have specifically selected TimescaleDB over other Databases for its multi-node capabilities under Kubernetes. Does that mean that multi-node support will be dropped from TimescaleDB? Or is it just that the chart is deprecated and there are other ways to install a multi-node version of TimescaleDB? If yes, then how is it done?

**Comment by paulfantom** [comment]
I am closing this issue as TimescaleDB-Multinode helm chart is no longer maintained and deprecated. We are looking for potential community maintainers who could help us in getting that helm chart working again. If you wish to become a maintainer, please [contact us on slack](https://timescaledb.slack.com/).

Keep in mind that TimescaleDB is not and will not be dropping multinode setup. Deprecation is only about helm chart.

**Comment by realulim** [comment]
For the record and for the benefit of others, who might automatically assume that "Kubernetes Support" means multinode:

I have talked to Timescale HQ and their official response was that "running TimescaleDB on a multinode Kubernetes cluster is not supported". Therefore deprecation is not only about the Helm chart.

You are correct insofar as Timescale internally runs its cloud offering on a multinode Kubernetes cluster, so technically there is a way to get it done. But it is not meant for customers.

**Comment by jfaldanam** [comment]
> For the record and for the benefit of others, who might automatically assume that "Kubernetes Support" means multinode:
> 
> I have talked to Timescale HQ and their official response was that "running TimescaleDB on a multinode Kubernetes cluster is not supported". Therefore deprecation is not only about the Helm chart.
> 
> You are correct insofar as Timescale internally runs its cloud offering on a multinode Kubernetes cluster, so technically there is a way to get it done. But it is not meant for customers.


For other people finding this issue, I have received a different answer from the Timescale devs: https://github.com/timescale/docs/pull/2132#issuecomment-1469188674
