### ISSUE TITLE
Patronictl list is not showing a "leader node"

### ISSUE THREAD

**Issue by byazici** [timescale/helm-charts#418]
**Did you expect to see something different?**

I installed **timescaledb-single** on Google Cloud with almost default settings.
When I run **patronictl list**. Two unexpected things I see:

`postgres@timescaledb-helm-0:~$ patronictl list
+--------------------+------------+---------+---------+----+-----------+
| Member             | Host       | Role    | State   | TL | Lag in MB |
+ Cluster: timescaledb-helm (uninitialized) +---------+----+-----------+
| timescaledb-helm-0 | 10.40.1.62 | Replica | running |  1 |         0 |
| timescaledb-helm-1 | 10.40.5.87 | Replica | running |  1 |         0 |
| timescaledb-helm-2 | 10.40.3.62 | Replica | running |  1 |         0 |
+--------------------+------------+---------+---------+----+-----------+
`
Q1. helm-0 is leader when I check with psql but its not showing here
Q2. why it says **uninitialized**?

**Environment**
* Which helm chart and what version are you using?
`version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"dirty", GoVersion:"go1.19"}
`

* What is in your `values.yaml` ?
[charts](https://github.com/timescale/helm-charts/tree/master/charts)/timescaledb-single/

* Kubernetes version information:
  `kubectl version`
   `Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"archive", BuildDate:"2022-08-08T17:09:48Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}`

* Kubernetes cluster kind:
 Google Kubernetes Cluster

**Anything else we need to know?**:
Replication is working altough this output.

**Comment by justinvogt87** [comment]
Try passing in the default `patroni.yaml` file: `patronictl -c /etc/timescaledb/patroni.yaml list`

**Comment by byazici** [comment]
It didn't work. It looks someting is getting broken while helm install. Actually I'm using "postgres-operator"  helm package and it works.

**Comment by nhudson** [comment]
Just tested this locally and on an AWS instance I have access to, I cannot replicate the issue.

AWS (EKS)
```
postgres@tobs-timescaledb-0:~$ patronictl -c /etc/timescaledb/patroni.yaml list
+--------------------+--------------+--------+---------+----+-----------+
| Member             | Host         | Role   | State   | TL | Lag in MB |
+ Cluster: tobs (7116895307194880033) -------+---------+----+-----------+
| tobs-timescaledb-0 | 172.28.4.166 | Leader | running |  3 |           |
+--------------------+--------------+--------+---------+----+-----------+
```

Local (kind)
```
postgres@test-timescaledb-0:~$ patronictl -c /etc/timescaledb/patroni.yaml list
+--------------------+-------------+---------+---------+----+-----------+
| Member             | Host        | Role    | State   | TL | Lag in MB |
+ Cluster: test (7135124973223039052) -------+---------+----+-----------+
| test-timescaledb-0 | 10.244.0.10 | Leader  | running |  1 |           |
| test-timescaledb-1 | 10.244.0.13 | Replica | running |  1 |         0 |
| test-timescaledb-2 | 10.244.0.16 | Replica | running |  1 |         0 |
+--------------------+-------------+---------+---------+----+-----------+
```

**Comment by byazici** [comment]
> It didn't work. It looks someting is getting broken while helm install. Actually I'm using "postgres-operator" helm package and it works.

Actually, I delete everyting and pull poject again and apply this (https://github.com/zalando/patroni/issues/1132) to prevent sericeaccount thing. As a result it didnt work without **-c** parameter but it worked with **-c** parameter now. Thanks
