### ISSUE TITLE
Capabilities Issue 

### ISSUE THREAD

**Issue by robgordon89** [timescale/helm-charts#433]
OK so I should have tested this PR before sorry about that 

@nhudson as you last approved it maybe you can help out a moment 

https://github.com/timescale/helm-charts/pull/432

On this issue, I incorrectly moved this to the outside of global scope, if this chart is used as a sub chart it will now error.

The original issue i was having appeared to be from the schema, so i think the error message i received gave me the wrong information 😆 

Im not sure how to fix it currently as I'm away from desk but wanted to update here

**Comment by robgordon89** [comment]
I think maybe it just needs 

```json
    "global" : {
        "additionalProperties": true
    },
```

in values.schema.json

**Comment by nhudson** [comment]
Thanks for the ping!  I can look into it but it will be tomorrow most likely.

**Comment by robgordon89** [comment]
@nhudson found the issue it was schema, it has been tested now 👍 

Sorry about the issue, I thought this would be a quick fix (always the way 😆 )

**Comment by nhudson** [comment]
@robgordon89 ah yes, I forget that as well. Great find and thanks for the contributions!
