### ISSUE TITLE
Flux V2 Support

### ISSUE THREAD

**Issue by deeco** [timescale/helm-charts#459]
Tried to install Timescale via Helm Controller in Flux

**Did you expect to see some different?**

**Environment**

k8s and flux v2

* Which helm chart and what version are you using?

latest

* What is in your `values.yaml` ?

default

* Kubernetes version information:

  `kubectl version`
 1.23.4
    
    
    
  `---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: timescale/tobs
  namespace: tobs
spec:
  interval: 1m
  url: https://charts.timescale.com/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: timescale/tobs
  namespace: tobs
spec:
  interval: 1m
  url: https://github.com/timescale/helm-charts
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/`  
  

* Kubernetes cluster kind:

  insert how you created your cluster: kops, bootkube, etc.

**Anything else we need to know?**:

**Comment by deeco** [comment]
Any updates

**Comment by paulfantom** [comment]
Please follow the answer you got in https://github.com/timescale/tobs/issues/587#issuecomment-1252650931.

I am closing as this is a duplicate.
