### ISSUE TITLE
Pod fails to launch with 'pod has unbound PersistentVolumeClaims'

### ISSUE THREAD

**Issue by warrenronsiek** [timescale/helm-charts#509]
**What did you do?**

I ran a `helm install timescale timescale/timescaledb-single -f timescale-values.yaml` where timescale values are [here](https://gist.github.com/warrenronsiek/8f19bd48463d84bcfa71219aca81ed79). When I did this, I got an error in the timescale pod where its stuck with 'pod has unbound PersistentVolumeClaims'.

**Did you expect to see some different?**

Yes, pod should launch without issue.

**Environment**

Ubuntu server 22.04 with a 1.8TB LVM mounted on `/home/warren/storage-mount`

** Which helm chart and what version are you using? **

```
> helm search repo timescale
NAME                           	CHART VERSION	APP VERSION	DESCRIPTION
timescale/timescaledb-multinode	0.8.0        	           	TimescaleDB Multinode Deployment.
timescale/timescaledb-single   	0.23.0       	           	TimescaleDB HA Deployment.
timescale/avalanche            	0.6.0        	           	A Helm chart run avalanche for benchmarking Pro...
timescale/promscale            	14.4.2       	0.16.0     	Promscale Connector deployment
timescale/tobs                 	17.21.0      	           	A Helm chart for tobs, The Observability Stack ...
```

** What is in your `values.yaml` ? **

Its the same as the default with the exception being a different mount path and data volume sizes. See [this gist](https://gist.github.com/warrenronsiek/8f19bd48463d84bcfa71219aca81ed79).

** Kubernetes version information: **

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7+rke2r1", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-13T18:58:02Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
```
** Kubernetes cluster kind: **

Rancher RKE2

**Comment by nhudson** [comment]
> ** Kubernetes cluster kind: **
>
>Rancher RKE2

The issue states you are using both Kind and RKE?  Which are you using to bootstrap the cluster?  Are you saying you're using Docker from Rancher Desktop and then using Kind to standup a local cluster, or are you using RKE from Rancher Desktop?

Can you post a `values.yaml` of just your changes?
