### ISSUE TITLE
(timescaledb-single) Helm wants to rename (remove and create) all objects (0.27.0)

### ISSUE THREAD

**Issue by tomislater** [timescale/helm-charts#531]
**What happened?**
I was not using this `nameOverride` feature before and now in (`0.27.0`) helm wants to remove **all objects** from a namespace and create new ones. Looks like this is related to https://github.com/timescale/helm-charts/pull/526.

According to [these changes](https://github.com/timescale/helm-charts/commit/16d53b26e9c2b11eb3c0ec88c2b422bf844f1c6c)  I think we should use:
```
fullnameOverride: "{{ .Release.Name }}"
```

instead of:
```
fullnameOverride: "{{ .Release.Name }}-timescaledb"
```
in default `values.yaml`.

**Did you expect to see something different?**
It should not touch me if I did not change `nameOverride` before. I never changed a value of this key.

**How to reproduce it (as minimally and precisely as possible)**:
Install chart in `0.26.x` version and then try to install it in `0.27.0`.

**Comment by tomislater** [comment]
My release name is `timescaledb-metrics`. I can just add
```
fullnameOverride: "{{ .Release.Name }}"
```
to my `values.yaml` file and everything works as before, but I think I should not do that because I never used this field (`nameOverride` or `fullnameOverride`).

**Comment by tomislater** [comment]
According to this note: https://github.com/timescale/helm-charts/blob/main/charts/timescaledb-single/docs/upgrade-guide.md#upgrading-to-027 everything should work as before. But, it is breaking change 👀

**Comment by paulfantom** [comment]
Thank you for your report! We are working on improving our test suite to catch similar issues in the future earlier in the development cycle.

**Comment by mogggggg** [comment]
@paulfantom Should this be fixed now? I previously had `nameOverride` set to the default `timescaledb` and my release name was `timescale`. If I upgrade to the latest chart and set `fullNameOverride` to `timescale-timescaledb` it still wants to change the `cluster-name` label and it wants to recreate all the services/secrets (ie. renaming the service `timescale-config` to `timescale-timescaledb-config`)

```diff
  # Source: timescaledb-single/templates/podmonitor.yaml
  apiVersion: monitoring.coreos.com/v1
  kind: PodMonitor
  metadata:
    name: timescale-timescaledb
    labels:
+
      app: timescale-timescaledb
-     chart: timescaledb-single-0.26.8
+     chart: timescaledb-single-0.27.3
      release: timescale
      heritage: Helm
-     cluster-name: timescale
+     cluster-name: timescale-timescaledb
      app.kubernetes.io/name: "timescale-timescaledb"
-     app.kubernetes.io/version: 0.26.8
+     app.kubernetes.io/version: 0.27.3
```

**Comment by mindrunner** [comment]
still an issue. can we re-open the ticket please?
