### ISSUE TITLE
UPGRADE FAILED chart after 0.25.1 when tstune is enabled

### ISSUE THREAD

**Issue by zfy0701** [timescale/helm-charts#532]
**What happened?**
after I upgrade to newest helm chart, it reports 
```
  Error: UPGRADE FAILED: template: timescaledb-single/templates/statefulset-timescaledb.yaml:35:65: executing "timescaledb-single/templates/statefulset-timescaledb.yaml" at <sha256sum>: wrong type for value; expected string; got map[string]interface {}
```

looks like:
https://github.com/timescale/helm-charts/commit/3804664b7bc14886db909809b5d83b65383d109a#diff-3210395104e9712528afa7119350e6250761db18b886c36af3e1dc600733fcfaR35

it can't be a map

in other place, we always first convert to string 
https://github.com/timescale/helm-charts/blob/d573ecf41b5ce1fe75e1ea431f7bf92c81722d80/charts/promscale/templates/deployment-promscale.yaml#L25

**Did you expect to see something different?**
should not report error

**How to reproduce it (as minimally and precisely as possible)**:
start tsdb with default parameter

**Environment**

* Which helm chart and what version are you using?

* What is in your `values.yaml` ?

* Kubernetes version information:

  `kubectl version`

    

* Kubernetes cluster kind:

  insert how you created your cluster: kops, bootkube, etc.

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Fixed in #537
