### ISSUE TITLE
Major Postgres Version upgrade

### ISSUE THREAD

**Issue by mindrunner** [timescale/helm-charts#577]
The new timescaledb images contains pg 12-15 binaries, enabling using the newer images with older databases. I just successfully updated the image, retaining my pg14 data. 

It would be super nice to be able to upgrade my cluster now to pg15 and then switch to the newer database binary by using `pg_upgrade`. 

Is there any way of doing this or can we enable the helm chart to have some sort of in-place upgrade procedure?

**Comment by omkaark** [comment]
Yup same question ^. I need to use the pg15 timescale image but the major version only goes up till 14!

**Comment by throrin19** [comment]
Same question here. I'm in pg12 and I want to upgrade to continue deploy future timescaledb versions
