### ISSUE TITLE
Wal Volume Log Cleanup for Timescaledb multi node helm chart

### ISSUE THREAD

**Issue by yspassivelogic** [timescale/helm-charts#592]
I am using the timescaledb multi node helm chart, my WAL volume associated with the helm chart is starting to fill up and I can see the WAL Persistent Volume usage increasing.

How do I implement WAL log rotation and/or cleanup via timescaledb multi node helm chart so perodically the WAL volume is cleant up?

Thank you!

**Comment by izavadynskyi** [comment]
Hi. Do you have some updates regarding this question? How the problem with increasing wal file was solved?

**Comment by yspassivelogic** [comment]
no solution yet
