### ISSUE TITLE
Is it still maintained ?

### ISSUE THREAD

**Issue by throrin19** [timescale/helm-charts#596]
Is the project still on track? Would it be only this one but also timescaledb-ha?

It's been several weeks or even months that problems with Patroni are present but nothing seems to change, as well as several configuration questions which are not answered due to validation problems with the charts configurations.

This naturally leads to this question: Is the project still active? Or is it "paused" to favor timescaledb Cloud over self-hosted?

**Comment by sumerman** [comment]
Please see https://github.com/timescale/promscale/issues/1836

TL;DR: No, only critical bug fixes.

**Comment by sumerman** [comment]
Apologies, I had my wires crossed and replied as if you were asking about promscale.

**Comment by cryptobench** [comment]
Bump. Following this

**Comment by fungiboletus** [comment]
> Bump. Following this

You can also add a thumb up on the first message and click the "subscribe" button 🙂

**Comment by throrin19** [comment]
I think the github bot comment respond for us. 

Can you confirm @feikesteenbergen ?

**Comment by mindrunner** [comment]
It is hardly maintained. PR reviews take ages and (as of my experience) only happen when you run after it. A quite important fix for something I filed about half a year ago is still not released to the helm repos (even though it was already merged to master weeks ago).

**Comment by Snazzie** [comment]
Petition to fork and create update to date helm chart

**Comment by timclifford** [comment]
Is someone able to give an update on the situation from the maintainers? Just so people can get a measure and plan a little better

**Comment by mindrunner** [comment]
^^

**Comment by Snazzie** [comment]
bad bot

**Comment by Snazzie** [comment]
bad bot

**Comment by tobywinnow** [comment]
Is it time for us to fork this and create a community managed helm chart?
The lack of engagement with PRs seems quite deliberate here.

**Comment by mindrunner** [comment]
![image](https://github.com/timescale/helm-charts/assets/1413542/f89c9430-9530-4183-8fab-e9e5476e3222)

**Comment by throrin19** [comment]
Bad bot....
