### ISSUE TITLE
helm chart for timesclae-db version 2.10.1/2.10.2? 

### ISSUE THREAD

**Issue by shridhar038** [timescale/helm-charts#604]
Using "**Hierarchical continuous aggregates**" (continuous aggregates on top of other continuous aggregates) to summarize data at several degrees of granularity. The most recent helm chart is presently available for timescale-2.9.1, a version that does not support this functionality. When can I expect a **_helm chart for timesclae-db version 2.10.1/2.10.2? or with the latest version_**.

When running the scripts, I encounter the following error. With the newest timescaledb version 2.10.x, the same scripts function without a problem.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/36623205/235662746-8b9a8882-a1fe-4c7d-9f95-8a1355cfc0f6.png">

**Comment by YarekTyshchenko** [comment]
Have you tried setting the latest image version into helm values?
https://hub.docker.com/layers/timescale/timescaledb-ha/pg14.7-ts2.10.3-all/images/sha256-af2f1d4057fab8d9207e70faf41c8e849e300ab6aaca3f5ed988509a95751bae?context=explore

**Comment by shridhar038** [comment]
ok. I will try by altering the values.yaml  to point to the most recent timescaledb version and update you.Thank you

**Comment by shridhar038** [comment]
We tried [https://hub.docker.com/layers/timescale/timescaledb-ha/pg14.7-ts2.10.3-all/images/sha256-af2f1d4057fab8d9207e70faf41c8e849e300ab6aaca3f5ed988509a95751bae?context=explore](https://urldefense.com/v3/__https://hub.docker.com/layers/timescale/timescaledb-ha/pg14.7-ts2.10.3-all/images/sha256-af2f1d4057fab8d9207e70faf41c8e849e300ab6aaca3f5ed988509a95751bae?context=explore__;!!HKYIif90!0o5UCllta157X49FbfHD94rJuxTcHW-OYoyGl9PRc9TY8d9RUNnOpJuhLxOi6isjl2z-3r6_OVOQ34O9dOiKwSAUznpGgg$).Its working fine.Thank you

**Comment by YarekTyshchenko** [comment]
Great! Would you mind closing this issue?
